### ISSUE TITLE
Is there a way to save recording to a particular location in filesystem?

### ISSUE THREAD

**Issue by vijayakumarn** [muaz-khan/RecordRTC#150]
Hi, Am using RecordRTC to successfully record a stream.
Then am calling recordRTC.save("filename1") to save the file.
Is there a way I can save to a particular location like recordRTC.save("/mydirectory/audio/audio1.webm")

Thanks

**Comment by CarpeNecopinum** [comment]
This should not be possible due to security limitations in the browser (imagine saving malicious dll-files, etc. that way).  
If you feel like you can talk your users into installing an application on their computers, you might want to try and use electron (https://github.com/electron/electron). It should let you use the regular NodeJS APIs for file manipulation.
