### ISSUE TITLE
Duration Pause/Play

### ISSUE THREAD

**Issue by efoula** [muaz-khan/RecordRTC#190]
Great plugin, nice work man.

Actually I have a problem with the recording duration, if I set a duration and enabled the pause recording function, it will pause the recording but the duration still counting on the background and when I check the console, I found the stop recording function works automatically while I am pausing the recording.. shortly, I need to pause the recording duration while pausing the recording.

console:
Paused recording.
**Stopped recording video stream
stopRecording  @RecordRTC.js:100
(anonymous function)	@RecordRTC.js:230**
Resume recording.

**Comment by thijstriemstra** [comment]
Seeing the same issue, pauseRecording looks buggy.

**Comment by muaz-khan** [comment]
Seems a bug happens on Firefox. They are correctly changing `mediaRecorder.state` from `recording` to `paused` but, behind the scene, they are not pausing the existing/active recorders.

Quick workaround can be:

```javascript
var arrayOfBlobs = [];
mediaRecorder.ondataavailable = function(event) {
    if (event.data && event.data.size) {
        if (isPausedRecording === false) { // manually skip if paused
            arrayOfBlobs.push(event.data);
        }
    }
};
```

We are not appending to `arrayOfBlobs`. We are passing 60 minutes interval on the `start` method:

```javascript
mediaRecorder.start(3.6e+6);
```

So `ondataavailable` returns us a big/huge blob rather than shorter blobs.

**Comment by muaz-khan** [comment]
**It is browser-related (native) bug.** That's why closing this issue.
