### ISSUE TITLE
when it will be support Safari? :)

### ISSUE THREAD

**Issue by SkyDropGG** [muaz-khan/RecordRTC#247]

**Comment by Tuizi** [comment]
The problem is Safari itself it doesn't allow the access to the camera

**Comment by SkyDropGG** [comment]
What would work need writ polyfill on flash (action script) or native safari plugin.

**Comment by Tuizi** [comment]
@SkyDropGG it's a debate I guess. w3c create standards to support those features. If some browser doesn't implements them, it's our role to make pressure and requests these feature (you can vote for Edge, but nothing with Apple).

The goal is to develop for the future, not for old technologies. Nobody wants to work with Flash anymore. So asking your user to use a different browser because the one they use are not supporting the feature yet it's a good way of pressure.

I know that is easy to say, but that the reality, we have web standards, browser need to follow them.
