### ISSUE TITLE
Replace container with preview (ASP.NET MVC)

### ISSUE THREAD

**Issue by suhomlineugene** [muaz-khan/RecordRTC#252]
I use your plugin and it works great.

I have ASP.NET MVC website

But I have one trouble. When I click stop I need to see recorded video in block, where I see live video when recording, etc.
Like there [https://www.webrtc-experiment.com/RecordRTC/](url)

I try to do this with 

` $('#preview').replaceWith($('#container'));` and reverse, but it not works.

How I can do this?

**Comment by muaz-khan** [comment]
```javascript
$('#preview').html('<video controls autoplay src="' + recorder.toURL() + '"></video>');
```

**Comment by suhomlineugene** [comment]
You talk about this

`$('#container').replaceWith($('#preview').html('<video controls autoplay src="' + recorder.toURL() + '"></video>'));`

**Comment by suhomlineugene** [comment]
Can you help me?

**Comment by suhomlineugene** [comment]
`recorder is not defined at HTMLButtonElement`

Have this

**Comment by muaz-khan** [comment]
Please try this demo instead:

* https://github.com/muaz-khan/RecordRTC/tree/master/RecordRTC-to-ASPNETMVC/RecordRTC_to_ASPNETMVC

Otherwise take codes from this cshtml file:

* https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC-to-ASPNETMVC/RecordRTC_to_ASPNETMVC/Views/RecordRTC/Index.cshtml

Otherwise try this demo and convert "save.php" into ASPNET equivalent:

* https://github.com/muaz-khan/RecordRTC/tree/master/RecordRTC-to-PHP

Or try simple-demos:

* https://github.com/muaz-khan/RecordRTC/tree/master/simple-demos

Main ["index.html" file](https://github.com/muaz-khan/RecordRTC/blob/master/index.html) is complicate d and it should not be used if you are not willing to provide similar drop-downs (to choose between encoders [vp8,vp9,h264,etc] or otherwise record screen).

Please check this video presentation:

* https://www.youtube.com/watch?v=YrLzTgdJ-Kg

Please try this simple demo:

```html
<script src="https://cdn.webrtc-experiment.com/gumadapter.js"></script>
<script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js"></script>
<script>
var recorder;

function successCallback(stream) {
    // RecordRTC usage goes here
    var parameters = {
        type: 'video'
    };
    recorder = RecordRTC(stream, parameters);
    recorder.startRecording();
}

function errorCallback(error) {
    alert('failed to capture camera');
}

document.querySelector('#btn-start-recording').onclick = function() {
    var mediaConstraints = {
        video: true,
        audio: true
    };

    navigator.mediaDevices.getUserMedia(mediaConstraints).then(successCallback).catch(errorCallback);
};

document.querySelector('#btn-stop-recording').onclick = function() {
    recorder.stopRecording(function() {
        var recorderBlob = recorder.getBlob();
        // upload to server (PHP or ASPNET)
        // or preview using <video> element
        yourPreviewElement.src = URL.createObjectURL(recorderBlob);
    });
};
</script>
```
