### ISSUE TITLE
recording audio only works the first time, any subsequent recordings are 44bytes

### ISSUE THREAD

**Issue by mreinsch** [muaz-khan/RecordRTC#41]
I'm using RecordRTC to record audio. This works fine, at least the first time. Any subsequent recordings (without reloading the browser) result in a 44 bytes wav file ("audio/wav -> 44.0 Bytes"). I'm only using RecordRTC in Chrome btw.

The version from "Feb 12, 2015, 08:32:23" doesn't show this behaviour yet, it keeps recording just fine. But Chrome is deprecating some event this version is using, so updating would be good.

**Comment by mreinsch** [comment]
BTW, the issue reported in https://github.com/muaz-khan/RecordRTC/issues/24 sounded similar, but applying the suggested fix didn't work.

**Comment by philazzi44** [comment]
Which Chrome event is being deprecated? I believe the Chrome dev team is actively implementing the MediaRecorder API which will eventually deprecate the stereo recorder altogether.

**Comment by mreinsch** [comment]
I see the following deprecation warning: 
'MediaStream.ended' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.

That might be fixed for quite some time, but Muaz isn't tagging releases in git, so a bit difficult to jump in and grab something working.

**Comment by muaz-khan** [comment]
I can confirm that [RecordRTC.js](https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC.js) is still working fine in the main demo. You can test `audio` here:

* [https://www.webrtc-experiment.com/RecordRTC/](https://www.webrtc-experiment.com/RecordRTC/)

Select `audio` and click `Start Recording` and try 5-6 times.

I did some **local** modifications in the same demo (`index.html`) to reuse `MediaStream` object but didn't face any single issue. Everything seems working fine for me. I tried both stable/canary channels. I tested in both Mac and Win7.

BTW, regarding coding updates, I added [`numberOfAudioChannels`](https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L40) but it shouldn't cause blank audio.

[`inputNode.disconnect()`](https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L463) seems also in valid place. It should also NOT affect next recording nodes.

I'm still [reusing AudioContext](https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L311); so it should NOT be the issue here.

[jsAudioNode](https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L348) is always initiated so don't need to place it outside the `StereoAudioRecorder` object.

The only strange thing happened is here [StereoAudioRecorder.js#L237](https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L237) which is ultimately revoked here [StereoAudioRecorder.js#L222](https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L222)

`MediaStream.active` is now checked here:

* [StereoAudioRecorder.js#L449](https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js#L449)

`onaudioprocess` event buffers are skipped in following cases:

1. `pauseRecording` is called. (i.e. `isPaused` object)
2. `MediaStream` is NOT active. See the block from above link. _I'm assuming the issue here._
3. `stopRecording` is called.

**Comment by mreinsch** [comment]
Thanks for the detailed answer, I should have checked the demo first I guess. I'll have a more detailed look into this next time I've got time to work on this and will let you know what my findings are.

**Comment by philazzi44** [comment]
I decided to try and update to the latest version in our solution, and I'm running into this issue as well. Based on my debugging, it appears that calling startRecording() on a RecordRTC instance that had stopRecording() called on it may not be supported. I'm likely going to try and just re-create our RecordRTC instance as needed rather than trying to re-use it, since that's likely the safest option.

**Comment by philazzi44** [comment]
Thanks for the commit. I'll try it out!

**Comment by philazzi44** [comment]
Looks like this may be incomplete. Looking at RecordRTC.startRecording, in cases where the mediaRecorder already exists (such as when you're starting a recording again after stopping it), the .resume() function is called but the .record() function never gets called. That one gets called from within initRecorder(), which is skipped. Looks like most of the internal recorders will kick off their .record() functions from within the .resume() function, but the WhammyRecorder doesn't seem to do this.

        function startRecording() {
        if (!config.disableLogs) {
            console.debug('started recording ' + config.type + ' stream.');
        }

        if (mediaRecorder) {
            mediaRecorder.clearRecordedData();
            mediaRecorder.resume();

            if (self.recordingDuration) {
                handleRecordingDuration();
            }
            return self;
        }

        initRecorder(function() {
            if (self.recordingDuration) {
                handleRecordingDuration();
            }
        });

        return self;
    }

**Comment by alexbazilev** [comment]
This is definitely still an issue.
I opened https://www.webrtc-experiment.com/RecordRTC/ on iOS, recorded more than 6 times and got an alert:
"null is not an object (evaluating 'context.createMediaStreamSource')".

Possibly the reason is that Safari doesn't allow to open multiple AudioContext instanses (more than 6). And it seems that calling "startRecording" function doesn't clear everything previously created correctly.

**Comment by krmckone** [comment]
I'm also having the issue of TypeError: null is not an object (evaluating audioContext.createMediaStreamSource when trying to record multiple times in safari on iOS. Any idea of how to work around this?
