### ISSUE TITLE
stopRecording not calling callback

### ISSUE THREAD

**Issue by amorino** [muaz-khan/RecordRTC#63]
I'm using RecordRTC as the example, however, the stopRecording function is not calling the callback function. 

The following messages are displaying:

> initializing video stream recorder message 
> started recording video stream.
> Stopped recording video stream.

But that's all. I'm using TweenMax and I get the following warning when I load RecordRTC:

> 'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.

Hope that helps.

**Comment by thierry2015** [comment]
I currently have the same issue, the callback is not called sometimes. I tried to isolate a typic case, the only one that I found was when stopRecording() was called less than 500ms after startRecording(), but the problem is still happening "randomly" for other cases. (I currently cannot isolate part of the problem)

I currently have a website that relies on this feature, I will continue to investigate the problem, but an update would be welcomed!

**Comment by cdanzig** [comment]
I have also gotten reports of the stopRecording callback not firing in Chrome. Have yet to reproduce.

**Comment by karls** [comment]
I have also stumbled on the same issue as previous posters. 

I have an external monitor (Thunderbolt display), which I use as my sole monitor most of the time -- laptop lid is closed. I can seemingly reproduce this behaviour when I select the Thunderbolt's camera, but Default or Built-in microphone (not Thunderbolt's own microphone). Having said that, this behaviour has also happened without using the external monitor, while working on the laptop.

I have noticed that when this behaviour (callback not getting called) happens, it is accompanied by ~1-2s freeze in the recorder initialisation. After that, the video starts, but then hangs again for a few seconds. When I stop the video, stream gets stopped, but the callback does not fire.

It looks like when there are multiple video/audio devices available and the "wrong" ones are selected, bad things happen. But given that this weird behaviour has also happened with just one camera and one microphone available, perhaps there is a deeper issue with how Chrome handles selecting media devices?

@muaz-khan any thoughts on this?

**Comment by mauliksoni110** [comment]
I am also facing the same, any workaround?

**Comment by karls** [comment]
@mauliksoni110 the "workaround" is to choose the correct device(s) before initialising the recorder. Unfortunately I don't yet know if or how this can be done programmatically, in the case of multiple available media devices. Given that this behaviour occasionally also happens with just one camera and one microphone, I'm not sure selecting the device programmatically would fix it.

**Comment by karls** [comment]
Actually, this does not seem to be a RecordRTC issue at all. I have not restarted by browser (Chrome) since I noticed this issue happening with our platform in order to investigate this issue. I can replicate the same behaviour on https://simpl.info/mediarecorder/ without using my external monitor, meaning that only 1 webcam and 1 mic is available for use. The result after recording looks like this -- no recorded blobs. Everything looks fine, I can see the stream in `<video>`, but after recording a clip, nothing shows up.

![No recorded blobs](https://drops.azureedge.net/drops/files/acc_482905/BuyX?rscd=inline%3B%20filename%3Dimage%252Fpng&rsct=image%2Fpng&se=2017-01-20T14%3A27%3A00Z&sig=DAwYZF%2BJkLEeiA%2FzmvvF32WKQPZBkOK%2BaHAbFW3y2t8%3D&sp=r&sr=b&st=2017-01-20T13%3A27%3A00Z&sv=2013-08-15)

**Comment by tdub7229** [comment]
Also experiencing this problem on Chrome 56.0.2924.87.  When this happens on my laptop (which only has one microphone and one camera), the recording light on my laptop stays on.

**Comment by karls** [comment]
Just to give an update to this -- some of our customers are having a fairly bad experience on Windows when another process has opened the webcam stream. Note that this *does not* seem to be the same issue as discussed here, but they *might* be related. I'm leaving this here for posterity.

I have also opened an issue on the Chromium bug tracker, https://bugs.chromium.org/p/chromium/issues/detail?id=690457, which also links to an issue on the Firefox bug tracker.

An operational update on my side is that we've stopped using RecordRTC for now and relying on just [adapter.js](https://github.com/webrtc/adapter). Adapter.js does not support Edge (no MediaRecorder), but we can live with it.

**Comment by cdanzig** [comment]
Just closed? No update?

**Comment by muaz-khan** [comment]
I think it is fixed here: https://github.com/muaz-khan/RecordRTC/commit/41c93ba01504bce84e406244ec3a3e2c5815340b

**Comment by ykmo-VIRNECT** [comment]
Well.. I'm facing same problem

**Comment by jaketrimble** [comment]
Also experiencing this issue with version 5.6.1 in Chrome 83.0.4103.61 (Official Build) (64-bit). Sometimes it fires the callback, but mostly it does not. Lots of debugging and no clues.
