### ISSUE TITLE
MediaStreamRecorder audio playback out of sync with video in Chrome/Mac

### ISSUE THREAD

**Issue by jhned** [muaz-khan/RecordRTC#738]
I'm experiencing some audio latency with Google Chrome on Mac. Tested Mac versions are 10.15.5, 10.14.6, and 11.2.3. Chrome version is 89.0.4389. Bug is reproducable on the demo page here: https://www.webrtc-experiment.com/RecordRTC/simple-demos/video-recording.html.

**Comment by marcuzy** [comment]
It needs some delay between mediaDevices.getUserMedia() and startRecording(). 
In this example https://webrtc.github.io/samples/src/content/getusermedia/record/ (using MediaRecorder directly) there is no delay, since getUserMedia is calling at application start.
Experimentally, I found out that 2 seconds is enough.

**Comment by jhned** [comment]
Excellent, thanks!

**Comment by qualitymanifest** [comment]
@marcuzy thank you so much, this issue had been driving me crazy and your suggestion fixed it. Strangely enough, I also found that if you are using the built-in mac screen recorder at the same time, it also fixes the issue. Obviously that is not a solution, just a funny anecdote.
