### ISSUE TITLE
Chrome h264 support

### ISSUE THREAD

**Issue by thijstriemstra** [muaz-khan/RecordRTC#97]
Chrome 50 supports h264 encoding/decoding: https://groups.google.com/forum/#!topic/discuss-webrtc/8ov4YW6HLgo

**Comment by muaz-khan** [comment]
We may need to pass `mimeType: 'video/mp4; codecs="mpeg4, aac"'`

```javascript
var recorder = RecordRTC(mediaStream, {
    type: 'video',
    mimeType: 'video/mp4; codecs="mpeg4, aac"'
});
```

**Comment by thijstriemstra** [comment]
I've tried this on Chrome/54.0.2840.41 on Ubuntu 16.04 but ffprobe keeps saying it's webm:

```
Input #0, matroska,webm, from '/home/thijs/Downloads/RecordRTC(3).webm':
  Metadata:
    encoder         : QTmuxingAppLibWebM-0.0.1
  Duration: N/A, start: 0.001000, bitrate: N/A
    Stream #0:0(eng): Video: vp8, yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, mono, fltp (default)
```

Same with Firefox 49 on the same platform (both `'video/mp4; codecs="mpeg4, aac"'` and `'video/mp4'`).

**Comment by thijstriemstra** [comment]
When using the mime type `video/webm;codecs=H264` it correctly creates an H264 file:

ffprobe output:

```
Input #0, matroska,webm, from 'index.mp4':
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: h264 (Constrained Baseline), yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 2k tbc (default)
```

A list of all available mime types in Chrome is listed [here](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/mediarecorder/MediaRecorder-isTypeSupported.html).

**Comment by thijstriemstra** [comment]
Yes but only ones listed on https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/mediarecorder/MediaRecorder-isTypeSupported.html

**Comment by bhanu-mnit** [comment]
Here it is mentioned that along with video, only OPUS is the acceptable audio codec. 

But for one of my project I need video in h264 and audio in wav or flac (because I need lossless data). Can I achieve this by parallely running two recorders one of audio and one of video?

Thanks.

**Comment by thijstriemstra** [comment]
No idea.

**Comment by notsoluckycharm** [comment]
@thijstriemstra 
Were you ever able to fix/generate Duration: N/A, start: 0.000000, bitrate: N/A from RecordRTC? I'm stuck on trying to generate this data without uploading it to the server to run ffmpeg, otherwise this solution is essentially a waste. Because this data is missing it is impossible to scrub the video or determine the length without downloading the entirety of a video file and playing it through,

**Comment by muaz-khan** [comment]
@bhanu-mnit You can initiate many parallel recorders:

```javascript
var h264Recorder = RecordRTC(videoOnlyStream, {
    type: 'video',
    mimeType: 'video/webm\;codecs=h264'
});

var wavRecorder = RecordRTC(stream, {
    type: 'audio',
    recorderType: StereoAudioRecorder
});
```

Or use `ffmpeg.js` to [convert into AAC](https://github.com/muaz-khan/Ffmpeg.js/blob/master/wav-to-aac.html).

**Comment by hoangbienit** [comment]
Dear Muaz Khan & all,
I can't pass record video H264 with the codes mediaRecorder.mimeType: 'video/mp4; codecs="mpeg4, aac"'; or mediaRecorder.mimeType: 'video/webm\;codecs=h264';:
`if (recorderType === 'WebP encoding into WebM') {
        mediaRecorder.recorderType = WhammyRecorder;
    }

    if(recorderType === 'mp4'){
        mediaRecorder.mimeType = 'video/mp4';
    }

    //mediaRecorder.mimeType: 'video/mp4; codecs="mpeg4, aac"';
    mediaRecorder.mimeType: 'video/webm\;codecs=h264';`

Please help me, What wrong in may code? How to fix it?
Thank you so much,

**Comment by mssodhi** [comment]
@hoangbienit change to `mediaRecorder.mimeType = 'video/webm\;codecs=h264';`

**Comment by thijstriemstra** [comment]
New demo for supported types on https://www.webrtc-experiment.com/RecordRTC/simple-demos/isTypeSupported.html

**Comment by guest271314** [comment]
Technically WebM container should contain only VP8, VP9, Vorbis, and Opus codecs. See https://bugzilla.mozilla.org/show_bug.cgi?id=1562862, https://bugs.chromium.org/p/chromium/issues/detail?id=980822

./mkvmerge -o full.webm 0.webm + 1.mp4
mkvmerge v35.0.0 ('All The Love In The World') 32-bit
Automatically enabling WebM compliance mode due to destination file name extension.
'0.webm': Using the demultiplexer for the format 'Matroska'.
'1.mp4': Using the demultiplexer for the format 'QuickTime/MP4'.
'0.webm' track 0: Using the output module for the format 'VP8/VP9'.
'1.webm' track 1: Using the output module for the format 'Opus'.
**Error: The codec type 'AVC/h.264' cannot be used in a WebM compliant file.**

**Comment by gautamgireesh** [comment]
> Hi,
> 
> So can I also pass other audio formats for webm file?
> 
> I passed this: mimeType: 'video/webm; codecs="VP9, wav"'
> 
> But it gave an error on browser end, in the console this appears multiple times:
> 
> > Blob encoder did not yet finished its job.

Getting the same error, have you managed to fix this?
